### ISSUE TITLE
plain bloom filter false positives

### ISSUE THREAD

**Issue by brentspell** [gmcabrita/bloomex#11]
It appears that the capacity of the plain bloom filter may be calculated incorrectly. This example

```elixir
bloom = Bloomex.plain(1000, 0.01)
Enum.reduce(1..1000, bloom, &Bloomex.add(&2, &1))
```

results in the following bloom filter struct

```elixir
%Bloomex.Bloom{
  bv: [
    {:array, 1, 0, 0, {3, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {:array, 1, 0, 0, {3, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {:array, 1, 0, 0, {3, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {:array, 1, 0, 0, {3, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {:array, 1, 0, 0, {3, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {:array, 1, 0, 0, {3, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
    {:array, 1, 0, 0, {3, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
  ],
  error_prob: 0.01,
  hash_func: #Function<1.7646300/1 in Bloomex.plain/2>,
  max: 1,
  mb: 1,
  size: 3
}
```

It appears that only 3 distinct numbers were actually added to the filter, even though it was initialized with a capacity of 1000 and a false positive rate of 1%. This configuration would be expected to hold around 990 distinct keys. It also seems wrong that the `:max` field is being set to 1 in this configuration.

If the above configuration is incorrect, or if I am misunderstanding the calculations for the plain filter, please let me know.

**Comment by gmcabrita** [comment]
Thanks for opening this issue!

You're right, the true capacity is being incorrectly calculated. Instead of using the given desired capacity to calculate the true capacity of the bloom filter I was using the false positive rate instead of the capacity.

After applying the fix the bloom filter struct appears to be correct:

```elixir
%Bloomex.Bloom{
  bv: [
    # ... omitted for simplicity of presentation
  ],
  error_prob: 0.01,
  hash_func: #Function<1.64750924/1 in Bloomex.plain/2>,
  max: 1494,
  mb: 11,
  size: 1000
```

I'll be pushing the fix soon.

**Comment by brentspell** [comment]
Thanks so much!

**Comment by gmcabrita** [comment]
I have also pushed the new version (1.0.5) to hex.pm.
